endpoints:
  shutdown:
    enabled: true
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:6060/eureka/
  instance:
    preferIpAddress: true
info:
  app:
    description: Cards Microservice application
    name: Cards
    version: 1.0.0
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
server:
  port: 5057
  
spring:
  application:
    name: cards
  datasource:
    password: banksCards
    url: jdbc:h2:mem:cards
    username: cards
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
